config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('',include('mywebsite.urls')),
    path('p2v/',include('p2v.urls')),
    path('digitrecognition/',include('digitrecognition.urls')),
]

digitrecognition/urls.py
from django.urls import path
from . import views

app_name = 'digit_recognition'

urlpatterns = [
    path('', views.DigitRecognition.as_view(), name='toppage'),
]

mywebsite/urls.py
from django.urls import path
from . import views

app_name = 'mywebsite'

urlpatterns = [
    path('', views.PageView.as_view(), name='toppage'),
    path('list/', views.ListArticle.as_view(), name='listpage'),
    path('detail/<int:pk>', views.DetailArticle.as_view(), name='detailpage'),
    path('delete/<int:pk>', views.DeleteAticle.as_view(), name='deletepage'),
    path('create/', views.CreateArticle.as_view(), name='createpage'),
    path('update/<int:pk>', views.UpdateArticle.as_view(), name='updatepage'),
    path('login/', views.LoginPage.as_view(), name='loginpage'),
    path('logout/', views.LogoutPage.as_view(), name='logoutpage'),
    
]

p2v/urls.py
from django.urls import path
from . import views

app_name = 'p2v'

urlpatterns = [
    path('', views.P2v.as_view(), name='toppage'),
    path('submitName',views.submitCalculatedAns),
]

digitrecognition/models.py
from django.db import models

# Create your models here.

mywebsite/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth import get_user_model

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    

p2v/models.py
from django.db import models

# Create your models here.

mywebsite/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
from .models import Article
"""
class Article(forms.Form):
    title = models.CharField(max_length=50)
    content = models.TextField()

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
"""
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

digitrecognition/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.

class DigitRecognition(generic.TemplateView):
    template_name = 'pages/recognition.html'

mywebsite/views.py
from django.shortcuts import render
from django.views import generic
from .models import Article
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from .forms import LoginForm
# Create your views here.

class PageView(generic.ListView):
    template_name = 'pages/index.html'
    model = Article

    def get_template_names(self):
        
        if self.request.user.is_authenticated:
            template_name = 'pages/loggedPage.html'
        else:
            template_name = self.template_name

        return [template_name]

class CreateArticle(generic.CreateView):
    template_name = 'pages/create.html'
    model = Article
    fields = ('title', 'content','author', )

    success_url = reverse_lazy('mywebsite:listpage')

    def get_template_names(self):
        
        if self.request.user.is_authenticated:
            template_name = 'pages/loggedCreate.html'
        else:
            template_name = self.template_name

        return [template_name]

class ListArticle(generic.ListView):
    template_name = 'pages/list.html'
    model = Article

class DetailArticle(generic.DetailView):
    template_name = 'pages/detail.html'
    model = Article
    context_object_name = 'item' # default_name is object

    def get_template_names(self):
        
        if self.request.user.is_authenticated:
            template_name = 'pages/loggedDetail.html'
        else:
            template_name = self.template_name

        return [template_name]

class DeleteAticle(generic.DeleteView):
    template_name = 'pages/delete.html'
    model = Article
    context_object_name = 'item'
    success_url = reverse_lazy('mywebsite:toppage')

    def get_template_names(self):
        
        if self.request.user.is_superuser:
            template_name = 'pages/loggedDelete.html'
        else:
            template_name = self.template_name

        return [template_name]

class UpdateArticle(generic.UpdateView):
    template_name = 'pages/update.html'
    model = Article
    fields = ('title', 'content', )
    success_url = reverse_lazy('mywebsite:toppage')

    def get_template_names(self):
        
        if self.request.user.is_superuser:
            template_name = 'pages/loggedUpdate.html'
        else:
            template_name = self.template_name

        return [template_name]

class LoginPage(LoginView):
    form_class = LoginForm
    template_name = 'pages/login.html'

    def get_template_names(self):
        
        if self.request.user.is_authenticated:
            template_name = 'pages/loggedlogin.html'
        else:
            template_name = self.template_name

        return [template_name]

class LogoutPage(LogoutView):
    template_name = 'pages/logout.html'
    

p2v/views.py
from django.shortcuts import render
from django.views import generic
from gensim.models import word2vec
from django.http.response import HttpResponse
# Create your views here.


# load model    --- model version is 11 ---
model = word2vec.Word2Vec.load('v11.model')


class P2v(generic.TemplateView):
    template_name = 'pages/p2v.html'

    def get_context_data(self, **kwargs):
        # load character name 
        character_name = []
        with open('static/character_name.txt','r',encoding="utf-8") as names:
            for name in names:
                character_name.append(name.rstrip())

        # load character type
        character_type = []
        with open('static/character_type.txt','r',encoding="utf-8") as names:
            for name in names:
                character_type.append(name.rstrip())

        context = super().get_context_data(**kwargs)
        context['character_name'] = character_name
        context['character_type'] = character_type

        return context

def submitCalculatedAns(request):
    poke_name = request.GET.get('c_name')
    poke_type = request.GET.get('c_type')
    output = model.most_similar(positive=[poke_name, poke_type])
    outname = []
    out = []
    for lis in output:

        a = str(lis[0])+"： 類似度 "+str(round(lis[1]*100,1))+"％,"
        out.append(a)

    return HttpResponse(out[:3])






digitrecognition/templates/pages/recognition.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h2>digit recognition</h2>
    <div class="row">
        <div class="col-md-6">
            <canvas
                id="input"
                width="400px"
                height="400px"
                style="border: solid 1px"
            ></canvas>
            <p>
            <button class="btn mt-3 btn-outline-success" id ="reset">reset</button>
        </div> 

        <div id ="outcome" class="col-md-6">
            <div class="row">
                <div class="col-4">
                    <div id="0">0 : 0%</div>
                    <div id="1">1 : 0%</div>
                    <div id="2">2 : 0%</div>
                    <div id="3">3 : 0%</div>
                    <div id="4">4 : 0%</div>
                </div>
                <div class="col-4">
                    <div id="5">5 : 0%</div>
                    <div id="6">6 : 0%</div>
                    <div id="7">7 : 0%</div>
                    <div id="8">8 : 0%</div>
                    <div id="9">9 : 0%</div>
                </div>
            <p></p>
                <div class="col-4">
                    you wrote
                    <div id="ans">0</div>
                </div>
            </div>

        </div>
    </div>
</div>

<script>
window.addEventListener("load",() =>{
    const canvas = document.getElementById("input");
    const context = canvas.getContext("2d");
    const position = {x:null,y:null};
    context.fillStyle = "black";
    context.fillRect(0, 0, canvas.clientWidth, canvas.clientHeight);
    let isDrag = false;
    

    function draw(x,y){
        if(!isDrag){
            return;
        }
        context.lineWidth = 15;
        context.lineCap = "round";
        context.lineJoin = "round";
        context.strokeStyle = "white";

        if(position.x ===null || position.y ===null){
            context.moveTo(x,y);
        }else{
            context.moveTo(position.x,position.y);
        }

        context.lineTo(x,y);
        context.stroke();
        position.x = x;
        position.y = y;
    }

    function reset(){
        context.fillRect(0, 0, canvas.clientWidth, canvas.clientHeight);
    }

    function drag_start(){
        context.beginPath();
        isDrag = true;
    }

    function drag_end(){
        context.closePath();
        isDrag = false;
        position.x = null;
        position.y = null;

    }

    async function fnc(){

        const tmpContext = document.createElement("canvas").getContext("2d");
        tmpContext.drawImage(canvas,0,0,28,28);
    
        let imgData = tmpContext.getImageData(0,0,28,28);
    
        let data = imgData.data;
    
        DATA = []
        for (i=0;i<data.length;i+=4){
            DATA.push(data[i])
        }
    
        data_tf = tf.tensor(DATA).reshape([1,28,28,1]);
        const model = await tf.loadLayersModel("../static/model2/model.json");
        const input = data_tf.div(tf.scalar(255));
        const prediction = await model.predict(input).data();

        let elm0 = document.getElementById("0");
        elm0.textContent = "0 : "+Math.round(prediction[0]*100)+"%";

        let elm1 = document.getElementById("1");
        elm1.textContent = "1 : "+Math.round(prediction[1]*100)+"%";

        let elm2 = document.getElementById("2");
        elm2.textContent = "2 : "+Math.round(prediction[2]*100)+"%";

        let elm3 = document.getElementById("3");
        elm3.textContent = "3 : "+Math.round(prediction[3]*100)+"%";

        let elm4 = document.getElementById("4");
        elm4.textContent = "4 : "+Math.round(prediction[4]*100)+"%";

        let elm5 = document.getElementById("5");
        elm5.textContent = "5 : "+Math.round(prediction[5]*100)+"%";

        let elm6 = document.getElementById("6");
        elm6.textContent = "6 : "+Math.round(prediction[6]*100)+"%";

        let elm7 = document.getElementById("7");
        elm7.textContent = "7 : "+Math.round(prediction[7]*100)+"%";

        let elm8 = document.getElementById("8");
        elm8.textContent = "8 : "+Math.round(prediction[8]*100)+"%";

        let elm9 = document.getElementById("9");
        elm9.textContent = "9 : "+Math.round(prediction[9]*100)+"%";

        let elmans = document.getElementById("ans");
        elmans.textContent = prediction.indexOf(prediction.reduce((a,b)=>Math.max(a,b)));
        
        l2 = model.layers[5].getWeights()[0].data();
 
        l5 = model.layers[4];
        console.log(l5);
    }

    const reset_botton = document.getElementById("reset");
    reset_botton.addEventListener("click",reset);

    canvas.addEventListener("mouseup",fnc);

    canvas.addEventListener("mousedown",drag_start);
    canvas.addEventListener("touchstart",drag_start);

    canvas.addEventListener("mouseup",drag_end);
    canvas.addEventListener("mouseout",drag_end);
    canvas.addEventListener("touchend",drag_end);
    canvas.addEventListener("touchend",fnc);

    canvas.addEventListener("mousemove",(event)=>{
        draw(event.layerX,event.layerY);
    })

    canvas.addEventListener("touchmove",function(event) {
        event.preventDefault();
        draw(event.layerX,event.layerY);
    }, false);


})  
</script>
{% endblock content %}

mywebsite/templates/pages/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.0.0/dist/tf.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'mywebsite:toppage' %}">page title</a>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mywebsite:toppage' %}">top</a>
            </li>
            <!--
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mywebsite:listpage' %}">list</a>
            </li>
            -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mywebsite:createpage' %}">create</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mywebsite:loginpage' %}">login/logout</a>
            </li>
          </ul>
        </div>
      </nav>

    {% block content %}
    {% endblock %}

</body>
</html>


<style>
    body {
        background-color: #ffffff;
        color: #333333;
    }
    .navbar-light {
        background-color: #ffffff !important;
    }
    .nav-item:hover{
        box-shadow:  inset 0.25vw 0.25vw 1vw #d4d4d4, inset -0.25vw -0.5vw 1vw #ffffff;
        border-radius:1vw;
    }

    a {
        color: #333333;
    }
    .container {
    max-width: 960px;
    }

    .pricing-header {
    max-width: 700px;
    }

    .card-deck .card {
    min-width: 220px;
    }

    .media{
        border-radius:2vw;
        box-shadow:  -0.5vw -0.5vw 1vw #d4d4d4, 0.5vw 0.5vw 1vw #ffffff;
        margin: 1.5vh;
        padding: 3vh;
    }
    .card {
        border-radius:2vw;
        box-shadow:  -0.5vw -0.5vw 1vw #d4d4d4, 0.5vw 0.5vw 1vw #ffffff;
        margin: 1.5vh;
        padding: 3vh;
    }
    .card-header {
        background-color: #ffffff;
    }
</style>

mywebsite/templates/pages/create.html
{% extends 'pages/base.html' %}
{% block content %}

この機能はログインしないと使えません

{% endblock %}

mywebsite/templates/pages/delete.html
{% extends 'pages/base.html' %}
{% block content %}
この機能はスーパーユーザーでログインしないと使えません
{% endblock %}

mywebsite/templates/pages/detail.html
{% extends 'pages/base.html' %}
{% block content %}
    
    <div class="container mx-auto">
        <p>detailpage</p>
    <div style="border-radius:2vw;
    box-shadow:  -0.5vw -0.5vw 1vw #d4d4d4, 0.5vw 0.5vw 1vw #ffffff; margin: 1.5vh; padding: 3vh;">

        <h5 class="mt-0">title: {{ item.title }}</h5>
        <p>{{ item.content }}</p>
        <div class="small">
            Witten by {{ item.author }} {{ item.created_time }}<br>
            updated time: {{ item.updated_time }}
        </div>
        <p></p>
    </div>
</div>
{% endblock %}

mywebsite/templates/pages/index.html
{% extends 'pages/base.html' %}
{% block content %}

<div class="container">
    <p>top page</p>

    <div class=" mb-3">

        <div class="card mb-4">
            <div class="card-header">
                <p>このページについて</ｐ>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-1">
                    <li>作ったものとその説明を書いたページです</li>
                    <li>Djangoで作っており，ログインをするとCRUD処理をすることができます</li>
                    <li>現状はHerokuで動かしていますがAWSに移植予定</li>
                    <li>　</li>
                    <li>ゲストログイン用の情報はログイン画面に置いてあります</li>
                    <li>該当記事の詳細ページから更新，削除ができます（スーパーユーザーのみ）</li>
                </ul>
            </div>
        </div>
        <div class="card mb-4">
            <div class="card-header">
                <a href="{% url 'p2v:toppage' %}" class="stretched-link">p2v</a>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>あるポケ〇ンに任意のタイプを追加で与えるとそれらからどのようなポケ〇ンが連想されるかを提示するシステム</ｈ>
                    <li>システムは単語の分散表現（Word2Vec）を用いており，事前に学習させたモデルをPython側で動かしてブラウザへ返している</li>
                </ul>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <a href="{% url 'digit_recognition:toppage' %}" class="stretched-link">mnist demo</a>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Tensorflow.jsというライブラリを用いてフロント側でモデルをロードし簡単な手書き数字を認識するシステム</li>
                    <li></li>
                </ul>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <a href="http://sm1057.skr.u-ryukyu.ac.jp/" class="stretched-link">サポートまるわかり</a>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>沖縄市に住む保護者さんに子育て支援制度・子どもの居場所の情報を提供するシステム</li>
                    <li>同市には見やすい・軽量・まとまった情報が掲載されたページが存在しなかった</li>
                    <li>SPA化することで画面遷移を高速にし，MDS（多次元尺度法）をもちいて似た傾向のものを近くに表示することで上記課題の解決を試みた</li>
                    <li>開発依頼を受けた際，子育て支援をしたいという意思に共感し技術的な面を全面的に担当（使用フレームワーク：Vue.js）</li>
                </ul>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <a href="https://ryukyushimpo.jp/pages/ryuvote.html" class="stretched-link">りゅうvote</a>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>沖縄県議選の候補者たちと同じ質問に回答することでユーザーと候補者との考えがどの程度似ているかをユーザーに示すシステム</li>
                    <li>地元新聞社との共同開発で技術的な面を全面的に担当</li>
                </ul>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <p>製作中</ｐ>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Posenetを用いた’何か’を製作中</li>
                    <li>ブラウザでも動くようにはなったもののまだ構想の段階</li>
                </ul>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <p>その他URL</ｐ>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    1. <a href="https://ryukyushimpo.jp/news/entry-1138674.html">りゅうVOTEの評判</a><br>
                    2. <a href="https://www.u-ryukyu.ac.jp/news/19834/">サポートまるわかり：大学記者懇談会</a><br>
                    3. <a href="http://www.nanospin.riec.tohoku.ac.jp/JNNS2020/files/program.pdf">研究（口頭発表）</a><br>
                    4. <a>準備中（ハッカソンで作成したWebRTCを用いたマッチングシステム）</a><br>
                </ul>
            </div>
        </div>
    </div>

<ul style="padding: 0;">
    {% for item in object_list %}
    
    <div class="media">
        <!--<svg class="bd-placeholder-img mr-3" width="64" height="64" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 64x64"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">64x64</text></svg>
        -->
        <!--<div class="media-body" style="border: #333333 solid 1px; margin: 1vh; padding: 1vh; border-radius: 1vh;">-->
        <div class="media-body">
          <h5 class="mt-0">
              <a href="{% url 'mywebsite:detailpage' item.pk %}" style="color: #333333;">
              {{ item.title }}</a></h5>
              
          {{ item.content | truncatechars:100}}<br>
          <div class="small" style="color: #757575;">Witten by {{ item.author }}  {{ item.created_time }}</div>
        </div>
    </div>
    
    {% endfor %}
</ul>
</div>
{% endblock %}

mywebsite/templates/pages/list.html
{% extends 'pages/base.html' %}
{% block content %}
    <p>listPage</p>
    <ul>
        {% for item in object_list %}
        <li><a href="{% url 'mywebsite:detailpage' item.pk %}">{{ item.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

mywebsite/templates/pages/loggedCreate.html
{% extends 'pages/base.html' %}
{% block content %}

<div class="container">
    <p>create page</p>
    <form method="POST">
        {% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="btn btn-outline-primary">submit</button>
    </form>
</div>
{% endblock %}

mywebsite/templates/pages/loggedDelete.html
{% extends 'pages/base.html' %}
{% block content %}
    <p>delete page</p>
        
    以下を削除
    <ul>
        <li>title: {{ item.title }}</li>
        <li>content: {{ item.content }}</li>
        <li>created time: {{ item.created_time }}</li>
        <li>updated time: {{ item.updated_time }}</li>
        <li>author: {{ item.author }}</li>
    </ul>

    <form method='POST'>
        {% csrf_token %}
        <button type="submit">delete</button>
    </form>
    <a href="{% url 'mywebsite:detailpage' item.pk %}">return</a>
{% endblock %}

mywebsite/templates/pages/loggedPage.html
{% extends 'pages/base.html' %}
{% block content %}

<div class="container">
    <p>ログイン中</p>

    <div class=" mb-3">

        <div class="card mb-4">
            <div class="card-header">
                <p>このページについて</ｐ>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>作ったものとその説明を書いたページです</li>
                    <li>Djangoで作っており，ログインをするとCRUD処理をすることができます</li>
                    <li>現状はHerokuで動かしていますがAWSに移植予定</li>
                </ul>
            </div>
        </div>
        <div class="card mb-4">
            <div class="card-header">
                <a href="{% url 'p2v:toppage' %}" class="stretched-link">p2v</a>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>あるポケ〇ンに任意のタイプを追加で与えるとそれらからどのようなポケ〇ンが連想されるかを提示するシステム</ｈ>
                    <li>システムは単語の分散表現（Word2Vec）を用いており，事前に学習させたモデルをPython側で動かしてブラウザへ返している</li>
                </ul>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <a href="{% url 'digit_recognition:toppage' %}" class="stretched-link">mnist demo</a>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Tensorflow.jsというライブラリを用いてフロント側でモデルをロードし簡単な手書き数字を認識するシステム</li>
                    <li></li>
                </ul>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <a href="http://sm1057.skr.u-ryukyu.ac.jp/" class="stretched-link">サポートまるわかり</a>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>沖縄市に住む保護者さんに子育て支援制度・子どもの居場所の情報を提供するシステム</li>
                    <li>同市には見やすい・軽量・まとまった情報が掲載されたページが存在しなかった</li>
                    <li>SPA化することで画面遷移を高速にし，MDS（多次元尺度法）をもちいて似た傾向のものを近くに表示することで上記課題の解決を試みた</li>
                    <li>開発依頼を受けた際，子育て支援をしたいという意思に共感し技術的な面を全面的に担当（使用フレームワーク：Vue.js）</li>
                </ul>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <a href="https://ryukyushimpo.jp/pages/ryuvote.html" class="stretched-link">りゅうvote</a>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>沖縄県議選の候補者たちと同じ質問に回答することでユーザーと候補者との考えがどの程度似ているかをユーザーに示すシステム</li>
                    <li>地元新聞社との共同開発で技術的な面を全面的に担当</li>
                </ul>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <p>製作中</ｐ>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Posenetを用いた’何か’を製作中</li>
                    <li>ブラウザでも動くようにはなったもののまだ構想の段階</li>
                </ul>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <p>その他URL</ｐ>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    1. <a href="https://ryukyushimpo.jp/news/entry-1138674.html">りゅうVOTEの評判</a><br>
                    2. <a href="https://www.u-ryukyu.ac.jp/news/19834/">サポートまるわかり：大学記者懇談会</a><br>
                    3. <a href="http://www.nanospin.riec.tohoku.ac.jp/JNNS2020/files/program.pdf">研究（口頭発表）</a><br>
                    4. <a>準備中（ハッカソンで作成したWebRTCを用いたマッチングシステム）</a><br>
                </ul>
            </div>
        </div>
    </div>

<ul style="padding: 0;">
    {% for item in object_list %}
    
    <div class="media">
        <!--<svg class="bd-placeholder-img mr-3" width="64" height="64" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 64x64"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">64x64</text></svg>
        -->
        <!--<div class="media-body" style="border: #333333 solid 1px; margin: 1vh; padding: 1vh; border-radius: 1vh;">-->
        <div class="media-body">
          <h5 class="mt-0">
              <a href="{% url 'mywebsite:detailpage' item.pk %}" style="color: #333333;">
              {{ item.title }}</a></h5>
              
          {{ item.content | truncatechars:100}}<br>
          <div class="small" style="color: #757575;">Witten by {{ item.author }}  {{ item.created_time }}</div>
        </div>
    </div>
    
    {% endfor %}
</ul>
</div>
{% endblock %}

mywebsite/templates/pages/loggedlogin.html
{% extends 'pages/base.html' %}
{% block content %}

ログアウトする
<a href="{% url 'mywebsite:logoutpage' %}">logout</a>

{% endblock %}